
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shop_s

test:
  <<: *default
  database: shop_s

# 
#
production:
  <<: *default
  database: shop_s
  username: deployer
  password: <%= ENV['TEST_DEPLOY_DATABASE_PASSWORD'] %>
